version: '3.8'

services:
  library-management-api:
    build: .
    environment:
      - PORT=7777
      - MONGO_URI=mongodb://mongoroot:testpassword@mongo-database:27017/library-management?authSource=admin
      - JWT_SECRET=6f6sd5f65sd6f56
    ports:
      - "7777:7777"
    depends_on:
      - mongo-database
    volumes:
      - .:/app
    networks:
      - lm-network

  mongo-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=testpassword
      - MONGO_INITDB_DATABASE=library-management
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lm-network

volumes:
  mongo-data:

networks:
  lm-network:
    driver: bridge