version: '3.8'

services:
  library-management-api:
    build: .
    environment:
      - PORT=7777
      - THROTTLE_TTL=60000
      - THROTTLE_LIMIT=10
      - MONGO_URI=mongodb://mongoroot:testpassword@mongo-database:27017/library-management?authSource=admin
      - JWT_SECRET=6f6sd5f65sd6f561
      - CORS_ORIGIN=*
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
      - REDIS_TTL=3000
      - REDIS_PASSWORD=testpassword
    ports:
      - "7777:7777"
    depends_on:
      - mongo-database
      - redis-cache
    volumes:
      - .:/app
    networks:
      - lm-network

  mongo-database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=testpassword
      - MONGO_INITDB_DATABASE=library-management
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lm-network

  redis-cache:
    image: redis:8.6.2-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass testpassword --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - lm-network
  
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis-cache
    networks:
      - lm-network

volumes:
  mongo-data:
  redis_data:

networks:
  lm-network:
    driver: bridge